version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: local_pdf_chatbot
    env_file:
      - .env
    ports:
      - "${STREAMLIT_SERVER_PORT:-8501}:8501"
    volumes:
      - ./app:/app
      - ./chunks:/app/chunks
      - ./vectordb:/app/vectordb
    restart: unless-stopped
